version: '3.8'

services:
  database:
    container_name: db
    image: postgres:13.4-alpine
    restart: always
    user: postgres
    volumes:
      - db_data:/var/lib/postgresql/data
    environment:
      - LC_ALL=C.UTF-8
      - POSTGRES_PASSWORD=postgres123
      - POSTGRES_USER=postgres
      - POSTGRES_DB=blog_db
    ports:
      - 5432:5432
    networks:
      - default

volumes:
  db_data:
